<?php
$territories = [
    'Afghanistan' => [
        'name' => 'Afghanistan',
        'continent' => 'Asia',
        'continent_code' => '142',
        'subcontinent' => 'Southern Asia',
        'subcontinent_code' => '034',
        'country_code' => 'AF',
    ],
    'Albania' => [
        'name' => 'Albania',
        'continent' => 'Europe',
        'continent_code' => '150',
        'subcontinent' => 'Southern Europe',
        'subcontinent_code' => '039',
        'country_code' => 'AL',
    ],
    'Algeria' => [
        'name' => 'Algeria',
        'continent' => 'Africa',
        'continent_code' => '002',
        'subcontinent' => 'Northern Africa',
        'subcontinent_code' => '015',
        'country_code' => 'DZ',
    ],
    'American Samoa' => [
        'name' => 'American Samoa',
        'continent' => 'Oceania',
        'continent_code' => '009',
        'subcontinent' => 'Polynesia',
        'subcontinent_code' => '061',
        'country_code' => 'AS',
    ],
    'Andorra' => [
        'name' => 'Andorra',
        'continent' => 'Europe',
        'continent_code' => '150',
        'subcontinent' => 'Southern Europe',
        'subcontinent_code' => '039',
        'country_code' => 'AD',
    ],
    'Angola' => [
        'name' => 'Angola',
        'continent' => 'Africa',
        'continent_code' => '002',
        'subcontinent' => 'Middle Africa',
        'subcontinent_code' => '017',
        'country_code' => 'AO',
    ],
    'Anguilla' => [
        'name' => 'Anguilla',
        'continent' => 'Americas',
        'continent_code' => '019',
        'subcontinent' => 'Caribbean',
        'subcontinent_code' => '029',
        'country_code' => 'AI',
    ],
    'Antarctica' => [
        'name' => 'Antarctica',
        'continent' => 'Oceania',
        'continent_code' => '009',
        'subcontinent' => 'Outlying Oceania',
        'subcontinent_code' => 'QO',
        'country_code' => 'AQ',
    ],
    'Antigua & Barbuda' => [
        'name' => 'Antigua & Barbuda',
        'continent' => 'Americas',
        'continent_code' => '019',
        'subcontinent' => 'Caribbean',
        'subcontinent_code' => '029',
        'country_code' => 'AG',
    ],
    'Argentina' => [
        'name' => 'Argentina',
        'continent' => 'Americas',
        'continent_code' => '019',
        'subcontinent' => 'South America',
        'subcontinent_code' => '005',
        'country_code' => 'AR',
    ],
    'Armenia' => [
        'name' => 'Armenia',
        'continent' => 'Asia',
        'continent_code' => '142',
        'subcontinent' => 'Western Asia',
        'subcontinent_code' => '145',
        'country_code' => 'AM',
    ],
    'Aruba' => [
        'name' => 'Aruba',
        'continent' => 'Americas',
        'continent_code' => '019',
        'subcontinent' => 'Caribbean',
        'subcontinent_code' => '029',
        'country_code' => 'AW',
    ],
    'Ascension Island' => [
        'name' => 'Ascension Island',
        'continent' => 'Oceania',
        'continent_code' => '009',
        'subcontinent' => 'Outlying Oceania',
        'subcontinent_code' => 'QO',
        'country_code' => 'AC',
    ],
    'Australia' => [
        'name' => 'Australia',
        'continent' => 'Oceania',
        'continent_code' => '009',
        'subcontinent' => 'Australasia',
        'subcontinent_code' => '053',
        'country_code' => 'AU',
    ],
    'Austria' => [
        'name' => 'Austria',
        'continent' => 'Europe',
        'continent_code' => '150',
        'subcontinent' => 'Western Europe',
        'subcontinent_code' => '155',
        'country_code' => 'AT',
    ],
    'Azerbaijan' => [
        'name' => 'Azerbaijan',
        'continent' => 'Asia',
        'continent_code' => '142',
        'subcontinent' => 'Western Asia',
        'subcontinent_code' => '145',
        'country_code' => 'AZ',
    ],
    'Bahamas' => [
        'name' => 'Bahamas',
        'continent' => 'Americas',
        'continent_code' => '019',
        'subcontinent' => 'Caribbean',
        'subcontinent_code' => '029',
        'country_code' => 'BS',
    ],
    'Bahrain' => [
        'name' => 'Bahrain',
        'continent' => 'Asia',
        'continent_code' => '142',
        'subcontinent' => 'Western Asia',
        'subcontinent_code' => '145',
        'country_code' => 'BH',
    ],
    'Bangladesh' => [
        'name' => 'Bangladesh',
        'continent' => 'Asia',
        'continent_code' => '142',
        'subcontinent' => 'Southern Asia',
        'subcontinent_code' => '034',
        'country_code' => 'BD',
    ],
    'Barbados' => [
        'name' => 'Barbados',
        'continent' => 'Americas',
        'continent_code' => '019',
        'subcontinent' => 'Caribbean',
        'subcontinent_code' => '029',
        'country_code' => 'BB',
    ],
    'Belarus' => [
        'name' => 'Belarus',
        'continent' => 'Europe',
        'continent_code' => '150',
        'subcontinent' => 'Eastern Europe',
        'subcontinent_code' => '151',
        'country_code' => 'BY',
    ],
    'Belgium' => [
        'name' => 'Belgium',
        'continent' => 'Europe',
        'continent_code' => '150',
        'subcontinent' => 'Western Europe',
        'subcontinent_code' => '155',
        'country_code' => 'BE',
    ],
    'Belize' => [
        'name' => 'Belize',
        'continent' => 'Americas',
        'continent_code' => '019',
        'subcontinent' => 'Central America',
        'subcontinent_code' => '013',
        'country_code' => 'BZ',
    ],
    'Benin' => [
        'name' => 'Benin',
        'continent' => 'Africa',
        'continent_code' => '002',
        'subcontinent' => 'Western Africa',
        'subcontinent_code' => '011',
        'country_code' => 'BJ',
    ],
    'Bermuda' => [
        'name' => 'Bermuda',
        'continent' => 'Americas',
        'continent_code' => '019',
        'subcontinent' => 'Northern America',
        'subcontinent_code' => '021',
        'country_code' => 'BM',
    ],
    'Bhutan' => [
        'name' => 'Bhutan',
        'continent' => 'Asia',
        'continent_code' => '142',
        'subcontinent' => 'Southern Asia',
        'subcontinent_code' => '034',
        'country_code' => 'BT',
    ],
    'Bolivia' => [
        'name' => 'Bolivia',
        'continent' => 'Americas',
        'continent_code' => '019',
        'subcontinent' => 'South America',
        'subcontinent_code' => '005',
        'country_code' => 'BO',
    ],
    'Bosnia & Herzegovina' => [
        'name' => 'Bosnia & Herzegovina',
        'continent' => 'Europe',
        'continent_code' => '150',
        'subcontinent' => 'Southern Europe',
        'subcontinent_code' => '039',
        'country_code' => 'BA',
    ],
    'Botswana' => [
        'name' => 'Botswana',
        'continent' => 'Africa',
        'continent_code' => '002',
        'subcontinent' => 'Southern Africa',
        'subcontinent_code' => '018',
        'country_code' => 'BW',
    ],
    'Bouvet Island' => [
        'name' => 'Bouvet Island',
        'continent' => 'Americas',
        'continent_code' => '019',
        'subcontinent' => 'South America',
        'subcontinent_code' => '005',
        'country_code' => 'BV',
    ],
    'Brazil' => [
        'name' => 'Brazil',
        'continent' => 'Americas',
        'continent_code' => '019',
        'subcontinent' => 'South America',
        'subcontinent_code' => '005',
        'country_code' => 'BR',
    ],
    'British Indian Ocean Territory' => [
        'name' => 'British Indian Ocean Territory',
        'continent' => 'Africa',
        'continent_code' => '002',
        'subcontinent' => 'Eastern Africa',
        'subcontinent_code' => '014',
        'country_code' => 'IO',
    ],
    'British Virgin Islands' => [
        'name' => 'British Virgin Islands',
        'continent' => 'Americas',
        'continent_code' => '019',
        'subcontinent' => 'Caribbean',
        'subcontinent_code' => '029',
        'country_code' => 'VG',
    ],
    'Brunei' => [
        'name' => 'Brunei',
        'continent' => 'Asia',
        'continent_code' => '142',
        'subcontinent' => 'Southeast Asia',
        'subcontinent_code' => '035',
        'country_code' => 'BN',
    ],
    'Bulgaria' => [
        'name' => 'Bulgaria',
        'continent' => 'Europe',
        'continent_code' => '150',
        'subcontinent' => 'Eastern Europe',
        'subcontinent_code' => '151',
        'country_code' => 'BG',
    ],
    'Burkina Faso' => [
        'name' => 'Burkina Faso',
        'continent' => 'Africa',
        'continent_code' => '002',
        'subcontinent' => 'Western Africa',
        'subcontinent_code' => '011',
        'country_code' => 'BF',
    ],
    'Burundi' => [
        'name' => 'Burundi',
        'continent' => 'Africa',
        'continent_code' => '002',
        'subcontinent' => 'Eastern Africa',
        'subcontinent_code' => '014',
        'country_code' => 'BI',
    ],
    'Cambodia' => [
        'name' => 'Cambodia',
        'continent' => 'Asia',
        'continent_code' => '142',
        'subcontinent' => 'Southeast Asia',
        'subcontinent_code' => '035',
        'country_code' => 'KH',
    ],
    'Cameroon' => [
        'name' => 'Cameroon',
        'continent' => 'Africa',
        'continent_code' => '002',
        'subcontinent' => 'Middle Africa',
        'subcontinent_code' => '017',
        'country_code' => 'CM',
    ],
    'Canada' => [
        'name' => 'Canada',
        'continent' => 'Americas',
        'continent_code' => '019',
        'subcontinent' => 'Northern America',
        'subcontinent_code' => '021',
        'country_code' => 'CA',
    ],
    'Canary Islands' => [
        'name' => 'Canary Islands',
        'continent' => 'Africa',
        'continent_code' => '002',
        'subcontinent' => 'Northern Africa',
        'subcontinent_code' => '015',
        'country_code' => 'IC',
    ],
    'Cape Verde' => [
        'name' => 'Cape Verde',
        'continent' => 'Africa',
        'continent_code' => '002',
        'subcontinent' => 'Western Africa',
        'subcontinent_code' => '011',
        'country_code' => 'CV',
    ],
    'Caribbean Netherlands' => [
        'name' => 'Caribbean Netherlands',
        'continent' => 'Americas',
        'continent_code' => '019',
        'subcontinent' => 'Caribbean',
        'subcontinent_code' => '029',
        'country_code' => 'BQ',
    ],
    'Cayman Islands' => [
        'name' => 'Cayman Islands',
        'continent' => 'Americas',
        'continent_code' => '019',
        'subcontinent' => 'Caribbean',
        'subcontinent_code' => '029',
        'country_code' => 'KY',
    ],
    'Central African Republic' => [
        'name' => 'Central African Republic',
        'continent' => 'Africa',
        'continent_code' => '002',
        'subcontinent' => 'Middle Africa',
        'subcontinent_code' => '017',
        'country_code' => 'CF',
    ],
    'Ceuta & Melilla' => [
        'name' => 'Ceuta & Melilla',
        'continent' => 'Africa',
        'continent_code' => '002',
        'subcontinent' => 'Northern Africa',
        'subcontinent_code' => '015',
        'country_code' => 'EA',
    ],
    'Chad' => [
        'name' => 'Chad',
        'continent' => 'Africa',
        'continent_code' => '002',
        'subcontinent' => 'Middle Africa',
        'subcontinent_code' => '017',
        'country_code' => 'TD',
    ],
    'Chile' => [
        'name' => 'Chile',
        'continent' => 'Americas',
        'continent_code' => '019',
        'subcontinent' => 'South America',
        'subcontinent_code' => '005',
        'country_code' => 'CL',
    ],
    'China' => [
        'name' => 'China',
        'continent' => 'Asia',
        'continent_code' => '142',
        'subcontinent' => 'Eastern Asia',
        'subcontinent_code' => '030',
        'country_code' => 'CN',
    ],
    'Christmas Island' => [
        'name' => 'Christmas Island',
        'continent' => 'Oceania',
        'continent_code' => '009',
        'subcontinent' => 'Australasia',
        'subcontinent_code' => '053',
        'country_code' => 'CX',
    ],
    'Clipperton Island' => [
        'name' => 'Clipperton Island',
        'continent' => 'Oceania',
        'continent_code' => '009',
        'subcontinent' => 'Outlying Oceania',
        'subcontinent_code' => 'QO',
        'country_code' => 'CP',
    ],
    'Cocos (Keeling) Islands' => [
        'name' => 'Cocos (Keeling) Islands',
        'continent' => 'Oceania',
        'continent_code' => '009',
        'subcontinent' => 'Australasia',
        'subcontinent_code' => '053',
        'country_code' => 'CC',
    ],
    'Colombia' => [
        'name' => 'Colombia',
        'continent' => 'Americas',
        'continent_code' => '019',
        'subcontinent' => 'South America',
        'subcontinent_code' => '005',
        'country_code' => 'CO',
    ],
    'Comoros' => [
        'name' => 'Comoros',
        'continent' => 'Africa',
        'continent_code' => '002',
        'subcontinent' => 'Eastern Africa',
        'subcontinent_code' => '014',
        'country_code' => 'KM',
    ],
    'Congo - Brazzaville' => [
        'name' => 'Congo - Brazzaville',
        'continent' => 'Africa',
        'continent_code' => '002',
        'subcontinent' => 'Middle Africa',
        'subcontinent_code' => '017',
        'country_code' => 'CG',
    ],
    'Congo - Kinshasa' => [
        'name' => 'Congo - Kinshasa',
        'continent' => 'Africa',
        'continent_code' => '002',
        'subcontinent' => 'Middle Africa',
        'subcontinent_code' => '017',
        'country_code' => 'CD',
    ],
    'Cook Islands' => [
        'name' => 'Cook Islands',
        'continent' => 'Oceania',
        'continent_code' => '009',
        'subcontinent' => 'Polynesia',
        'subcontinent_code' => '061',
        'country_code' => 'CK',
    ],
    'Costa Rica' => [
        'name' => 'Costa Rica',
        'continent' => 'Americas',
        'continent_code' => '019',
        'subcontinent' => 'Central America',
        'subcontinent_code' => '013',
        'country_code' => 'CR',
    ],
    'Croatia' => [
        'name' => 'Croatia',
        'continent' => 'Europe',
        'continent_code' => '150',
        'subcontinent' => 'Southern Europe',
        'subcontinent_code' => '039',
        'country_code' => 'HR',
    ],
    'Cuba' => [
        'name' => 'Cuba',
        'continent' => 'Americas',
        'continent_code' => '019',
        'subcontinent' => 'Caribbean',
        'subcontinent_code' => '029',
        'country_code' => 'CU',
    ],
    'Curaçao' => [
        'name' => 'Curaçao',
        'continent' => 'Americas',
        'continent_code' => '019',
        'subcontinent' => 'Caribbean',
        'subcontinent_code' => '029',
        'country_code' => 'CW',
    ],
    'Cyprus' => [
        'name' => 'Cyprus',
        'continent' => 'Asia',
        'continent_code' => '142',
        'subcontinent' => 'Western Asia',
        'subcontinent_code' => '145',
        'country_code' => 'CY',
    ],
    'Czechia' => [
        'name' => 'Czechia',
        'continent' => 'Europe',
        'continent_code' => '150',
        'subcontinent' => 'Eastern Europe',
        'subcontinent_code' => '151',
        'country_code' => 'CZ',
    ],
    'Côte d’Ivoire' => [
        'name' => 'Côte d’Ivoire',
        'continent' => 'Africa',
        'continent_code' => '002',
        'subcontinent' => 'Western Africa',
        'subcontinent_code' => '011',
        'country_code' => 'CI',
    ],
    'Denmark' => [
        'name' => 'Denmark',
        'continent' => 'Europe',
        'continent_code' => '150',
        'subcontinent' => 'Northern Europe',
        'subcontinent_code' => '154',
        'country_code' => 'DK',
    ],
    'Diego Garcia' => [
        'name' => 'Diego Garcia',
        'continent' => 'Oceania',
        'continent_code' => '009',
        'subcontinent' => 'Outlying Oceania',
        'subcontinent_code' => 'QO',
        'country_code' => 'DG',
    ],
    'Djibouti' => [
        'name' => 'Djibouti',
        'continent' => 'Africa',
        'continent_code' => '002',
        'subcontinent' => 'Eastern Africa',
        'subcontinent_code' => '014',
        'country_code' => 'DJ',
    ],
    'Dominica' => [
        'name' => 'Dominica',
        'continent' => 'Americas',
        'continent_code' => '019',
        'subcontinent' => 'Caribbean',
        'subcontinent_code' => '029',
        'country_code' => 'DM',
    ],
    'Dominican Republic' => [
        'name' => 'Dominican Republic',
        'continent' => 'Americas',
        'continent_code' => '019',
        'subcontinent' => 'Caribbean',
        'subcontinent_code' => '029',
        'country_code' => 'DO',
    ],
    'Ecuador' => [
        'name' => 'Ecuador',
        'continent' => 'Americas',
        'continent_code' => '019',
        'subcontinent' => 'South America',
        'subcontinent_code' => '005',
        'country_code' => 'EC',
    ],
    'Egypt' => [
        'name' => 'Egypt',
        'continent' => 'Africa',
        'continent_code' => '002',
        'subcontinent' => 'Northern Africa',
        'subcontinent_code' => '015',
        'country_code' => 'EG',
    ],
    'El Salvador' => [
        'name' => 'El Salvador',
        'continent' => 'Americas',
        'continent_code' => '019',
        'subcontinent' => 'Central America',
        'subcontinent_code' => '013',
        'country_code' => 'SV',
    ],
    'Equatorial Guinea' => [
        'name' => 'Equatorial Guinea',
        'continent' => 'Africa',
        'continent_code' => '002',
        'subcontinent' => 'Middle Africa',
        'subcontinent_code' => '017',
        'country_code' => 'GQ',
    ],
    'Eritrea' => [
        'name' => 'Eritrea',
        'continent' => 'Africa',
        'continent_code' => '002',
        'subcontinent' => 'Eastern Africa',
        'subcontinent_code' => '014',
        'country_code' => 'ER',
    ],
    'Estonia' => [
        'name' => 'Estonia',
        'continent' => 'Europe',
        'continent_code' => '150',
        'subcontinent' => 'Northern Europe',
        'subcontinent_code' => '154',
        'country_code' => 'EE',
    ],
    'Eswatini' => [
        'name' => 'Eswatini',
        'continent' => 'Africa',
        'continent_code' => '002',
        'subcontinent' => 'Southern Africa',
        'subcontinent_code' => '018',
        'country_code' => 'SZ',
    ],
    'Ethiopia' => [
        'name' => 'Ethiopia',
        'continent' => 'Africa',
        'continent_code' => '002',
        'subcontinent' => 'Eastern Africa',
        'subcontinent_code' => '014',
        'country_code' => 'ET',
    ],
    'Falkland Islands' => [
        'name' => 'Falkland Islands',
        'continent' => 'Americas',
        'continent_code' => '019',
        'subcontinent' => 'South America',
        'subcontinent_code' => '005',
        'country_code' => 'FK',
    ],
    'Faroe Islands' => [
        'name' => 'Faroe Islands',
        'continent' => 'Europe',
        'continent_code' => '150',
        'subcontinent' => 'Northern Europe',
        'subcontinent_code' => '154',
        'country_code' => 'FO',
    ],
    'Fiji' => [
        'name' => 'Fiji',
        'continent' => 'Oceania',
        'continent_code' => '009',
        'subcontinent' => 'Melanesia',
        'subcontinent_code' => '054',
        'country_code' => 'FJ',
    ],
    'Finland' => [
        'name' => 'Finland',
        'continent' => 'Europe',
        'continent_code' => '150',
        'subcontinent' => 'Northern Europe',
        'subcontinent_code' => '154',
        'country_code' => 'FI',
    ],
    'France' => [
        'name' => 'France',
        'continent' => 'Europe',
        'continent_code' => '150',
        'subcontinent' => 'Western Europe',
        'subcontinent_code' => '155',
        'country_code' => 'FR',
    ],
    'French Guiana' => [
        'name' => 'French Guiana',
        'continent' => 'Americas',
        'continent_code' => '019',
        'subcontinent' => 'South America',
        'subcontinent_code' => '005',
        'country_code' => 'GF',
    ],
    'French Polynesia' => [
        'name' => 'French Polynesia',
        'continent' => 'Oceania',
        'continent_code' => '009',
        'subcontinent' => 'Polynesia',
        'subcontinent_code' => '061',
        'country_code' => 'PF',
    ],
    'French Southern Territories' => [
        'name' => 'French Southern Territories',
        'continent' => 'Africa',
        'continent_code' => '002',
        'subcontinent' => 'Eastern Africa',
        'subcontinent_code' => '014',
        'country_code' => 'TF',
    ],
    'Gabon' => [
        'name' => 'Gabon',
        'continent' => 'Africa',
        'continent_code' => '002',
        'subcontinent' => 'Middle Africa',
        'subcontinent_code' => '017',
        'country_code' => 'GA',
    ],
    'Gambia' => [
        'name' => 'Gambia',
        'continent' => 'Africa',
        'continent_code' => '002',
        'subcontinent' => 'Western Africa',
        'subcontinent_code' => '011',
        'country_code' => 'GM',
    ],
    'Georgia' => [
        'name' => 'Georgia',
        'continent' => 'Asia',
        'continent_code' => '142',
        'subcontinent' => 'Western Asia',
        'subcontinent_code' => '145',
        'country_code' => 'GE',
    ],
    'Germany' => [
        'name' => 'Germany',
        'continent' => 'Europe',
        'continent_code' => '150',
        'subcontinent' => 'Western Europe',
        'subcontinent_code' => '155',
        'country_code' => 'DE',
    ],
    'Ghana' => [
        'name' => 'Ghana',
        'continent' => 'Africa',
        'continent_code' => '002',
        'subcontinent' => 'Western Africa',
        'subcontinent_code' => '011',
        'country_code' => 'GH',
    ],
    'Gibraltar' => [
        'name' => 'Gibraltar',
        'continent' => 'Europe',
        'continent_code' => '150',
        'subcontinent' => 'Southern Europe',
        'subcontinent_code' => '039',
        'country_code' => 'GI',
    ],
    'Greece' => [
        'name' => 'Greece',
        'continent' => 'Europe',
        'continent_code' => '150',
        'subcontinent' => 'Southern Europe',
        'subcontinent_code' => '039',
        'country_code' => 'GR',
    ],
    'Greenland' => [
        'name' => 'Greenland',
        'continent' => 'Americas',
        'continent_code' => '019',
        'subcontinent' => 'Northern America',
        'subcontinent_code' => '021',
        'country_code' => 'GL',
    ],
    'Grenada' => [
        'name' => 'Grenada',
        'continent' => 'Americas',
        'continent_code' => '019',
        'subcontinent' => 'Caribbean',
        'subcontinent_code' => '029',
        'country_code' => 'GD',
    ],
    'Guadeloupe' => [
        'name' => 'Guadeloupe',
        'continent' => 'Americas',
        'continent_code' => '019',
        'subcontinent' => 'Caribbean',
        'subcontinent_code' => '029',
        'country_code' => 'GP',
    ],
    'Guam' => [
        'name' => 'Guam',
        'continent' => 'Oceania',
        'continent_code' => '009',
        'subcontinent' => 'Micronesian Region',
        'subcontinent_code' => '057',
        'country_code' => 'GU',
    ],
    'Guatemala' => [
        'name' => 'Guatemala',
        'continent' => 'Americas',
        'continent_code' => '019',
        'subcontinent' => 'Central America',
        'subcontinent_code' => '013',
        'country_code' => 'GT',
    ],
    'Guernsey' => [
        'name' => 'Guernsey',
        'continent' => 'Europe',
        'continent_code' => '150',
        'subcontinent' => 'Northern Europe',
        'subcontinent_code' => '154',
        'country_code' => 'GG',
    ],
    'Guinea' => [
        'name' => 'Guinea',
        'continent' => 'Africa',
        'continent_code' => '002',
        'subcontinent' => 'Western Africa',
        'subcontinent_code' => '011',
        'country_code' => 'GN',
    ],
    'Guinea-Bissau' => [
        'name' => 'Guinea-Bissau',
        'continent' => 'Africa',
        'continent_code' => '002',
        'subcontinent' => 'Western Africa',
        'subcontinent_code' => '011',
        'country_code' => 'GW',
    ],
    'Guyana' => [
        'name' => 'Guyana',
        'continent' => 'Americas',
        'continent_code' => '019',
        'subcontinent' => 'South America',
        'subcontinent_code' => '005',
        'country_code' => 'GY',
    ],
    'Haiti' => [
        'name' => 'Haiti',
        'continent' => 'Americas',
        'continent_code' => '019',
        'subcontinent' => 'Caribbean',
        'subcontinent_code' => '029',
        'country_code' => 'HT',
    ],
    'Heard & McDonald Islands' => [
        'name' => 'Heard & McDonald Islands',
        'continent' => 'Oceania',
        'continent_code' => '009',
        'subcontinent' => 'Australasia',
        'subcontinent_code' => '053',
        'country_code' => 'HM',
    ],
    'Honduras' => [
        'name' => 'Honduras',
        'continent' => 'Americas',
        'continent_code' => '019',
        'subcontinent' => 'Central America',
        'subcontinent_code' => '013',
        'country_code' => 'HN',
    ],
    'Hong Kong SAR China' => [
        'name' => 'Hong Kong SAR China',
        'continent' => 'Asia',
        'continent_code' => '142',
        'subcontinent' => 'Eastern Asia',
        'subcontinent_code' => '030',
        'country_code' => 'HK',
    ],
    'Hungary' => [
        'name' => 'Hungary',
        'continent' => 'Europe',
        'continent_code' => '150',
        'subcontinent' => 'Eastern Europe',
        'subcontinent_code' => '151',
        'country_code' => 'HU',
    ],
    'Iceland' => [
        'name' => 'Iceland',
        'continent' => 'Europe',
        'continent_code' => '150',
        'subcontinent' => 'Northern Europe',
        'subcontinent_code' => '154',
        'country_code' => 'IS',
    ],
    'India' => [
        'name' => 'India',
        'continent' => 'Asia',
        'continent_code' => '142',
        'subcontinent' => 'Southern Asia',
        'subcontinent_code' => '034',
        'country_code' => 'IN',
    ],
    'Indonesia' => [
        'name' => 'Indonesia',
        'continent' => 'Asia',
        'continent_code' => '142',
        'subcontinent' => 'Southeast Asia',
        'subcontinent_code' => '035',
        'country_code' => 'ID',
    ],
    'Iran' => [
        'name' => 'Iran',
        'continent' => 'Asia',
        'continent_code' => '142',
        'subcontinent' => 'Southern Asia',
        'subcontinent_code' => '034',
        'country_code' => 'IR',
    ],
    'Iraq' => [
        'name' => 'Iraq',
        'continent' => 'Asia',
        'continent_code' => '142',
        'subcontinent' => 'Western Asia',
        'subcontinent_code' => '145',
        'country_code' => 'IQ',
    ],
    'Ireland' => [
        'name' => 'Ireland',
        'continent' => 'Europe',
        'continent_code' => '150',
        'subcontinent' => 'Northern Europe',
        'subcontinent_code' => '154',
        'country_code' => 'IE',
    ],
    'Isle of Man' => [
        'name' => 'Isle of Man',
        'continent' => 'Europe',
        'continent_code' => '150',
        'subcontinent' => 'Northern Europe',
        'subcontinent_code' => '154',
        'country_code' => 'IM',
    ],
    'Israel' => [
        'name' => 'Israel',
        'continent' => 'Asia',
        'continent_code' => '142',
        'subcontinent' => 'Western Asia',
        'subcontinent_code' => '145',
        'country_code' => 'IL',
    ],
    'Italy' => [
        'name' => 'Italy',
        'continent' => 'Europe',
        'continent_code' => '150',
        'subcontinent' => 'Southern Europe',
        'subcontinent_code' => '039',
        'country_code' => 'IT',
    ],
    'Jamaica' => [
        'name' => 'Jamaica',
        'continent' => 'Americas',
        'continent_code' => '019',
        'subcontinent' => 'Caribbean',
        'subcontinent_code' => '029',
        'country_code' => 'JM',
    ],
    'Japan' => [
        'name' => 'Japan',
        'continent' => 'Asia',
        'continent_code' => '142',
        'subcontinent' => 'Eastern Asia',
        'subcontinent_code' => '030',
        'country_code' => 'JP',
    ],
    'Jersey' => [
        'name' => 'Jersey',
        'continent' => 'Europe',
        'continent_code' => '150',
        'subcontinent' => 'Northern Europe',
        'subcontinent_code' => '154',
        'country_code' => 'JE',
    ],
    'Jordan' => [
        'name' => 'Jordan',
        'continent' => 'Asia',
        'continent_code' => '142',
        'subcontinent' => 'Western Asia',
        'subcontinent_code' => '145',
        'country_code' => 'JO',
    ],
    'Kazakhstan' => [
        'name' => 'Kazakhstan',
        'continent' => 'Asia',
        'continent_code' => '142',
        'subcontinent' => 'Central Asia',
        'subcontinent_code' => '143',
        'country_code' => 'KZ',
    ],
    'Kenya' => [
        'name' => 'Kenya',
        'continent' => 'Africa',
        'continent_code' => '002',
        'subcontinent' => 'Eastern Africa',
        'subcontinent_code' => '014',
        'country_code' => 'KE',
    ],
    'Kiribati' => [
        'name' => 'Kiribati',
        'continent' => 'Oceania',
        'continent_code' => '009',
        'subcontinent' => 'Micronesian Region',
        'subcontinent_code' => '057',
        'country_code' => 'KI',
    ],
    'Kosovo' => [
        'name' => 'Kosovo',
        'continent' => 'Europe',
        'continent_code' => '150',
        'subcontinent' => 'Southern Europe',
        'subcontinent_code' => '039',
        'country_code' => 'XK',
    ],
    'Kuwait' => [
        'name' => 'Kuwait',
        'continent' => 'Asia',
        'continent_code' => '142',
        'subcontinent' => 'Western Asia',
        'subcontinent_code' => '145',
        'country_code' => 'KW',
    ],
    'Kyrgyzstan' => [
        'name' => 'Kyrgyzstan',
        'continent' => 'Asia',
        'continent_code' => '142',
        'subcontinent' => 'Central Asia',
        'subcontinent_code' => '143',
        'country_code' => 'KG',
    ],
    'Laos' => [
        'name' => 'Laos',
        'continent' => 'Asia',
        'continent_code' => '142',
        'subcontinent' => 'Southeast Asia',
        'subcontinent_code' => '035',
        'country_code' => 'LA',
    ],
    'Latvia' => [
        'name' => 'Latvia',
        'continent' => 'Europe',
        'continent_code' => '150',
        'subcontinent' => 'Northern Europe',
        'subcontinent_code' => '154',
        'country_code' => 'LV',
    ],
    'Lebanon' => [
        'name' => 'Lebanon',
        'continent' => 'Asia',
        'continent_code' => '142',
        'subcontinent' => 'Western Asia',
        'subcontinent_code' => '145',
        'country_code' => 'LB',
    ],
    'Lesotho' => [
        'name' => 'Lesotho',
        'continent' => 'Africa',
        'continent_code' => '002',
        'subcontinent' => 'Southern Africa',
        'subcontinent_code' => '018',
        'country_code' => 'LS',
    ],
    'Liberia' => [
        'name' => 'Liberia',
        'continent' => 'Africa',
        'continent_code' => '002',
        'subcontinent' => 'Western Africa',
        'subcontinent_code' => '011',
        'country_code' => 'LR',
    ],
    'Libya' => [
        'name' => 'Libya',
        'continent' => 'Africa',
        'continent_code' => '002',
        'subcontinent' => 'Northern Africa',
        'subcontinent_code' => '015',
        'country_code' => 'LY',
    ],
    'Liechtenstein' => [
        'name' => 'Liechtenstein',
        'continent' => 'Europe',
        'continent_code' => '150',
        'subcontinent' => 'Western Europe',
        'subcontinent_code' => '155',
        'country_code' => 'LI',
    ],
    'Lithuania' => [
        'name' => 'Lithuania',
        'continent' => 'Europe',
        'continent_code' => '150',
        'subcontinent' => 'Northern Europe',
        'subcontinent_code' => '154',
        'country_code' => 'LT',
    ],
    'Luxembourg' => [
        'name' => 'Luxembourg',
        'continent' => 'Europe',
        'continent_code' => '150',
        'subcontinent' => 'Western Europe',
        'subcontinent_code' => '155',
        'country_code' => 'LU',
    ],
    'Macao SAR China' => [
        'name' => 'Macao SAR China',
        'continent' => 'Asia',
        'continent_code' => '142',
        'subcontinent' => 'Eastern Asia',
        'subcontinent_code' => '030',
        'country_code' => 'MO',
    ],
    'Madagascar' => [
        'name' => 'Madagascar',
        'continent' => 'Africa',
        'continent_code' => '002',
        'subcontinent' => 'Eastern Africa',
        'subcontinent_code' => '014',
        'country_code' => 'MG',
    ],
    'Malawi' => [
        'name' => 'Malawi',
        'continent' => 'Africa',
        'continent_code' => '002',
        'subcontinent' => 'Eastern Africa',
        'subcontinent_code' => '014',
        'country_code' => 'MW',
    ],
    'Malaysia' => [
        'name' => 'Malaysia',
        'continent' => 'Asia',
        'continent_code' => '142',
        'subcontinent' => 'Southeast Asia',
        'subcontinent_code' => '035',
        'country_code' => 'MY',
    ],
    'Maldives' => [
        'name' => 'Maldives',
        'continent' => 'Asia',
        'continent_code' => '142',
        'subcontinent' => 'Southern Asia',
        'subcontinent_code' => '034',
        'country_code' => 'MV',
    ],
    'Mali' => [
        'name' => 'Mali',
        'continent' => 'Africa',
        'continent_code' => '002',
        'subcontinent' => 'Western Africa',
        'subcontinent_code' => '011',
        'country_code' => 'ML',
    ],
    'Malta' => [
        'name' => 'Malta',
        'continent' => 'Europe',
        'continent_code' => '150',
        'subcontinent' => 'Southern Europe',
        'subcontinent_code' => '039',
        'country_code' => 'MT',
    ],
    'Marshall Islands' => [
        'name' => 'Marshall Islands',
        'continent' => 'Oceania',
        'continent_code' => '009',
        'subcontinent' => 'Micronesian Region',
        'subcontinent_code' => '057',
        'country_code' => 'MH',
    ],
    'Martinique' => [
        'name' => 'Martinique',
        'continent' => 'Americas',
        'continent_code' => '019',
        'subcontinent' => 'Caribbean',
        'subcontinent_code' => '029',
        'country_code' => 'MQ',
    ],
    'Mauritania' => [
        'name' => 'Mauritania',
        'continent' => 'Africa',
        'continent_code' => '002',
        'subcontinent' => 'Western Africa',
        'subcontinent_code' => '011',
        'country_code' => 'MR',
    ],
    'Mauritius' => [
        'name' => 'Mauritius',
        'continent' => 'Africa',
        'continent_code' => '002',
        'subcontinent' => 'Eastern Africa',
        'subcontinent_code' => '014',
        'country_code' => 'MU',
    ],
    'Mayotte' => [
        'name' => 'Mayotte',
        'continent' => 'Africa',
        'continent_code' => '002',
        'subcontinent' => 'Eastern Africa',
        'subcontinent_code' => '014',
        'country_code' => 'YT',
    ],
    'Mexico' => [
        'name' => 'Mexico',
        'continent' => 'Americas',
        'continent_code' => '019',
        'subcontinent' => 'Central America',
        'subcontinent_code' => '013',
        'country_code' => 'MX',
    ],
    'Micronesia' => [
        'name' => 'Micronesia',
        'continent' => 'Oceania',
        'continent_code' => '009',
        'subcontinent' => 'Micronesian Region',
        'subcontinent_code' => '057',
        'country_code' => 'FM',
    ],
    'Moldova' => [
        'name' => 'Moldova',
        'continent' => 'Europe',
        'continent_code' => '150',
        'subcontinent' => 'Eastern Europe',
        'subcontinent_code' => '151',
        'country_code' => 'MD',
    ],
    'Monaco' => [
        'name' => 'Monaco',
        'continent' => 'Europe',
        'continent_code' => '150',
        'subcontinent' => 'Western Europe',
        'subcontinent_code' => '155',
        'country_code' => 'MC',
    ],
    'Mongolia' => [
        'name' => 'Mongolia',
        'continent' => 'Asia',
        'continent_code' => '142',
        'subcontinent' => 'Eastern Asia',
        'subcontinent_code' => '030',
        'country_code' => 'MN',
    ],
    'Montenegro' => [
        'name' => 'Montenegro',
        'continent' => 'Europe',
        'continent_code' => '150',
        'subcontinent' => 'Southern Europe',
        'subcontinent_code' => '039',
        'country_code' => 'ME',
    ],
    'Montserrat' => [
        'name' => 'Montserrat',
        'continent' => 'Americas',
        'continent_code' => '019',
        'subcontinent' => 'Caribbean',
        'subcontinent_code' => '029',
        'country_code' => 'MS',
    ],
    'Morocco' => [
        'name' => 'Morocco',
        'continent' => 'Africa',
        'continent_code' => '002',
        'subcontinent' => 'Northern Africa',
        'subcontinent_code' => '015',
        'country_code' => 'MA',
    ],
    'Mozambique' => [
        'name' => 'Mozambique',
        'continent' => 'Africa',
        'continent_code' => '002',
        'subcontinent' => 'Eastern Africa',
        'subcontinent_code' => '014',
        'country_code' => 'MZ',
    ],
    'Myanmar (Burma)' => [
        'name' => 'Myanmar (Burma)',
        'continent' => 'Asia',
        'continent_code' => '142',
        'subcontinent' => 'Southeast Asia',
        'subcontinent_code' => '035',
        'country_code' => 'MM',
    ],
    'Namibia' => [
        'name' => 'Namibia',
        'continent' => 'Africa',
        'continent_code' => '002',
        'subcontinent' => 'Southern Africa',
        'subcontinent_code' => '018',
        'country_code' => 'NA',
    ],
    'Nauru' => [
        'name' => 'Nauru',
        'continent' => 'Oceania',
        'continent_code' => '009',
        'subcontinent' => 'Micronesian Region',
        'subcontinent_code' => '057',
        'country_code' => 'NR',
    ],
    'Nepal' => [
        'name' => 'Nepal',
        'continent' => 'Asia',
        'continent_code' => '142',
        'subcontinent' => 'Southern Asia',
        'subcontinent_code' => '034',
        'country_code' => 'NP',
    ],
    'Netherlands' => [
        'name' => 'Netherlands',
        'continent' => 'Europe',
        'continent_code' => '150',
        'subcontinent' => 'Western Europe',
        'subcontinent_code' => '155',
        'country_code' => 'NL',
    ],
    'New Caledonia' => [
        'name' => 'New Caledonia',
        'continent' => 'Oceania',
        'continent_code' => '009',
        'subcontinent' => 'Melanesia',
        'subcontinent_code' => '054',
        'country_code' => 'NC',
    ],
    'New Zealand' => [
        'name' => 'New Zealand',
        'continent' => 'Oceania',
        'continent_code' => '009',
        'subcontinent' => 'Australasia',
        'subcontinent_code' => '053',
        'country_code' => 'NZ',
    ],
    'Nicaragua' => [
        'name' => 'Nicaragua',
        'continent' => 'Americas',
        'continent_code' => '019',
        'subcontinent' => 'Central America',
        'subcontinent_code' => '013',
        'country_code' => 'NI',
    ],
    'Niger' => [
        'name' => 'Niger',
        'continent' => 'Africa',
        'continent_code' => '002',
        'subcontinent' => 'Western Africa',
        'subcontinent_code' => '011',
        'country_code' => 'NE',
    ],
    'Nigeria' => [
        'name' => 'Nigeria',
        'continent' => 'Africa',
        'continent_code' => '002',
        'subcontinent' => 'Western Africa',
        'subcontinent_code' => '011',
        'country_code' => 'NG',
    ],
    'Niue' => [
        'name' => 'Niue',
        'continent' => 'Oceania',
        'continent_code' => '009',
        'subcontinent' => 'Polynesia',
        'subcontinent_code' => '061',
        'country_code' => 'NU',
    ],
    'Norfolk Island' => [
        'name' => 'Norfolk Island',
        'continent' => 'Oceania',
        'continent_code' => '009',
        'subcontinent' => 'Australasia',
        'subcontinent_code' => '053',
        'country_code' => 'NF',
    ],
    'North Korea' => [
        'name' => 'North Korea',
        'continent' => 'Asia',
        'continent_code' => '142',
        'subcontinent' => 'Eastern Asia',
        'subcontinent_code' => '030',
        'country_code' => 'KP',
    ],
    'North Macedonia' => [
        'name' => 'North Macedonia',
        'continent' => 'Europe',
        'continent_code' => '150',
        'subcontinent' => 'Southern Europe',
        'subcontinent_code' => '039',
        'country_code' => 'MK',
    ],
    'Northern Mariana Islands' => [
        'name' => 'Northern Mariana Islands',
        'continent' => 'Oceania',
        'continent_code' => '009',
        'subcontinent' => 'Micronesian Region',
        'subcontinent_code' => '057',
        'country_code' => 'MP',
    ],
    'Norway' => [
        'name' => 'Norway',
        'continent' => 'Europe',
        'continent_code' => '150',
        'subcontinent' => 'Northern Europe',
        'subcontinent_code' => '154',
        'country_code' => 'NO',
    ],
    'Oman' => [
        'name' => 'Oman',
        'continent' => 'Asia',
        'continent_code' => '142',
        'subcontinent' => 'Western Asia',
        'subcontinent_code' => '145',
        'country_code' => 'OM',
    ],
    'Pakistan' => [
        'name' => 'Pakistan',
        'continent' => 'Asia',
        'continent_code' => '142',
        'subcontinent' => 'Southern Asia',
        'subcontinent_code' => '034',
        'country_code' => 'PK',
    ],
    'Palau' => [
        'name' => 'Palau',
        'continent' => 'Oceania',
        'continent_code' => '009',
        'subcontinent' => 'Micronesian Region',
        'subcontinent_code' => '057',
        'country_code' => 'PW',
    ],
    'Palestinian Territories' => [
        'name' => 'Palestinian Territories',
        'continent' => 'Asia',
        'continent_code' => '142',
        'subcontinent' => 'Western Asia',
        'subcontinent_code' => '145',
        'country_code' => 'PS',
    ],
    'Panama' => [
        'name' => 'Panama',
        'continent' => 'Americas',
        'continent_code' => '019',
        'subcontinent' => 'Central America',
        'subcontinent_code' => '013',
        'country_code' => 'PA',
    ],
    'Papua New Guinea' => [
        'name' => 'Papua New Guinea',
        'continent' => 'Oceania',
        'continent_code' => '009',
        'subcontinent' => 'Melanesia',
        'subcontinent_code' => '054',
        'country_code' => 'PG',
    ],
    'Paraguay' => [
        'name' => 'Paraguay',
        'continent' => 'Americas',
        'continent_code' => '019',
        'subcontinent' => 'South America',
        'subcontinent_code' => '005',
        'country_code' => 'PY',
    ],
    'Peru' => [
        'name' => 'Peru',
        'continent' => 'Americas',
        'continent_code' => '019',
        'subcontinent' => 'South America',
        'subcontinent_code' => '005',
        'country_code' => 'PE',
    ],
    'Philippines' => [
        'name' => 'Philippines',
        'continent' => 'Asia',
        'continent_code' => '142',
        'subcontinent' => 'Southeast Asia',
        'subcontinent_code' => '035',
        'country_code' => 'PH',
    ],
    'Pitcairn Islands' => [
        'name' => 'Pitcairn Islands',
        'continent' => 'Oceania',
        'continent_code' => '009',
        'subcontinent' => 'Polynesia',
        'subcontinent_code' => '061',
        'country_code' => 'PN',
    ],
    'Poland' => [
        'name' => 'Poland',
        'continent' => 'Europe',
        'continent_code' => '150',
        'subcontinent' => 'Eastern Europe',
        'subcontinent_code' => '151',
        'country_code' => 'PL',
    ],
    'Portugal' => [
        'name' => 'Portugal',
        'continent' => 'Europe',
        'continent_code' => '150',
        'subcontinent' => 'Southern Europe',
        'subcontinent_code' => '039',
        'country_code' => 'PT',
    ],
    'Puerto Rico' => [
        'name' => 'Puerto Rico',
        'continent' => 'Americas',
        'continent_code' => '019',
        'subcontinent' => 'Caribbean',
        'subcontinent_code' => '029',
        'country_code' => 'PR',
    ],
    'Qatar' => [
        'name' => 'Qatar',
        'continent' => 'Asia',
        'continent_code' => '142',
        'subcontinent' => 'Western Asia',
        'subcontinent_code' => '145',
        'country_code' => 'QA',
    ],
    'Romania' => [
        'name' => 'Romania',
        'continent' => 'Europe',
        'continent_code' => '150',
        'subcontinent' => 'Eastern Europe',
        'subcontinent_code' => '151',
        'country_code' => 'RO',
    ],
    'Russia' => [
        'name' => 'Russia',
        'continent' => 'Europe',
        'continent_code' => '150',
        'subcontinent' => 'Eastern Europe',
        'subcontinent_code' => '151',
        'country_code' => 'RU',
    ],
    'Rwanda' => [
        'name' => 'Rwanda',
        'continent' => 'Africa',
        'continent_code' => '002',
        'subcontinent' => 'Eastern Africa',
        'subcontinent_code' => '014',
        'country_code' => 'RW',
    ],
    'Réunion' => [
        'name' => 'Réunion',
        'continent' => 'Africa',
        'continent_code' => '002',
        'subcontinent' => 'Eastern Africa',
        'subcontinent_code' => '014',
        'country_code' => 'RE',
    ],
    'Samoa' => [
        'name' => 'Samoa',
        'continent' => 'Oceania',
        'continent_code' => '009',
        'subcontinent' => 'Polynesia',
        'subcontinent_code' => '061',
        'country_code' => 'WS',
    ],
    'San Marino' => [
        'name' => 'San Marino',
        'continent' => 'Europe',
        'continent_code' => '150',
        'subcontinent' => 'Southern Europe',
        'subcontinent_code' => '039',
        'country_code' => 'SM',
    ],
    'Sark' => [
        'name' => 'Sark',
        'continent' => 'Europe',
        'continent_code' => '150',
        'subcontinent' => 'Northern Europe',
        'subcontinent_code' => '154',
        'country_code' => 'CQ',
    ],
    'Saudi Arabia' => [
        'name' => 'Saudi Arabia',
        'continent' => 'Asia',
        'continent_code' => '142',
        'subcontinent' => 'Western Asia',
        'subcontinent_code' => '145',
        'country_code' => 'SA',
    ],
    'Senegal' => [
        'name' => 'Senegal',
        'continent' => 'Africa',
        'continent_code' => '002',
        'subcontinent' => 'Western Africa',
        'subcontinent_code' => '011',
        'country_code' => 'SN',
    ],
    'Serbia' => [
        'name' => 'Serbia',
        'continent' => 'Europe',
        'continent_code' => '150',
        'subcontinent' => 'Southern Europe',
        'subcontinent_code' => '039',
        'country_code' => 'RS',
    ],
    'Seychelles' => [
        'name' => 'Seychelles',
        'continent' => 'Africa',
        'continent_code' => '002',
        'subcontinent' => 'Eastern Africa',
        'subcontinent_code' => '014',
        'country_code' => 'SC',
    ],
    'Sierra Leone' => [
        'name' => 'Sierra Leone',
        'continent' => 'Africa',
        'continent_code' => '002',
        'subcontinent' => 'Western Africa',
        'subcontinent_code' => '011',
        'country_code' => 'SL',
    ],
    'Singapore' => [
        'name' => 'Singapore',
        'continent' => 'Asia',
        'continent_code' => '142',
        'subcontinent' => 'Southeast Asia',
        'subcontinent_code' => '035',
        'country_code' => 'SG',
    ],
    'Sint Maarten' => [
        'name' => 'Sint Maarten',
        'continent' => 'Americas',
        'continent_code' => '019',
        'subcontinent' => 'Caribbean',
        'subcontinent_code' => '029',
        'country_code' => 'SX',
    ],
    'Slovakia' => [
        'name' => 'Slovakia',
        'continent' => 'Europe',
        'continent_code' => '150',
        'subcontinent' => 'Eastern Europe',
        'subcontinent_code' => '151',
        'country_code' => 'SK',
    ],
    'Slovenia' => [
        'name' => 'Slovenia',
        'continent' => 'Europe',
        'continent_code' => '150',
        'subcontinent' => 'Southern Europe',
        'subcontinent_code' => '039',
        'country_code' => 'SI',
    ],
    'Solomon Islands' => [
        'name' => 'Solomon Islands',
        'continent' => 'Oceania',
        'continent_code' => '009',
        'subcontinent' => 'Melanesia',
        'subcontinent_code' => '054',
        'country_code' => 'SB',
    ],
    'Somalia' => [
        'name' => 'Somalia',
        'continent' => 'Africa',
        'continent_code' => '002',
        'subcontinent' => 'Eastern Africa',
        'subcontinent_code' => '014',
        'country_code' => 'SO',
    ],
    'South Africa' => [
        'name' => 'South Africa',
        'continent' => 'Africa',
        'continent_code' => '002',
        'subcontinent' => 'Southern Africa',
        'subcontinent_code' => '018',
        'country_code' => 'ZA',
    ],
    'South Georgia & South Sandwich Islands' => [
        'name' => 'South Georgia & South Sandwich Islands',
        'continent' => 'Americas',
        'continent_code' => '019',
        'subcontinent' => 'South America',
        'subcontinent_code' => '005',
        'country_code' => 'GS',
    ],
    'South Korea' => [
        'name' => 'South Korea',
        'continent' => 'Asia',
        'continent_code' => '142',
        'subcontinent' => 'Eastern Asia',
        'subcontinent_code' => '030',
        'country_code' => 'KR',
    ],
    'South Sudan' => [
        'name' => 'South Sudan',
        'continent' => 'Africa',
        'continent_code' => '002',
        'subcontinent' => 'Eastern Africa',
        'subcontinent_code' => '014',
        'country_code' => 'SS',
    ],
    'Spain' => [
        'name' => 'Spain',
        'continent' => 'Europe',
        'continent_code' => '150',
        'subcontinent' => 'Southern Europe',
        'subcontinent_code' => '039',
        'country_code' => 'ES',
    ],
    'Sri Lanka' => [
        'name' => 'Sri Lanka',
        'continent' => 'Asia',
        'continent_code' => '142',
        'subcontinent' => 'Southern Asia',
        'subcontinent_code' => '034',
        'country_code' => 'LK',
    ],
    'St. Barthélemy' => [
        'name' => 'St. Barthélemy',
        'continent' => 'Americas',
        'continent_code' => '019',
        'subcontinent' => 'Caribbean',
        'subcontinent_code' => '029',
        'country_code' => 'BL',
    ],
    'St. Helena' => [
        'name' => 'St. Helena',
        'continent' => 'Africa',
        'continent_code' => '002',
        'subcontinent' => 'Western Africa',
        'subcontinent_code' => '011',
        'country_code' => 'SH',
    ],
    'St. Kitts & Nevis' => [
        'name' => 'St. Kitts & Nevis',
        'continent' => 'Americas',
        'continent_code' => '019',
        'subcontinent' => 'Caribbean',
        'subcontinent_code' => '029',
        'country_code' => 'KN',
    ],
    'St. Lucia' => [
        'name' => 'St. Lucia',
        'continent' => 'Americas',
        'continent_code' => '019',
        'subcontinent' => 'Caribbean',
        'subcontinent_code' => '029',
        'country_code' => 'LC',
    ],
    'St. Martin' => [
        'name' => 'St. Martin',
        'continent' => 'Americas',
        'continent_code' => '019',
        'subcontinent' => 'Caribbean',
        'subcontinent_code' => '029',
        'country_code' => 'MF',
    ],
    'St. Pierre & Miquelon' => [
        'name' => 'St. Pierre & Miquelon',
        'continent' => 'Americas',
        'continent_code' => '019',
        'subcontinent' => 'Northern America',
        'subcontinent_code' => '021',
        'country_code' => 'PM',
    ],
    'St. Vincent & Grenadines' => [
        'name' => 'St. Vincent & Grenadines',
        'continent' => 'Americas',
        'continent_code' => '019',
        'subcontinent' => 'Caribbean',
        'subcontinent_code' => '029',
        'country_code' => 'VC',
    ],
    'Sudan' => [
        'name' => 'Sudan',
        'continent' => 'Africa',
        'continent_code' => '002',
        'subcontinent' => 'Northern Africa',
        'subcontinent_code' => '015',
        'country_code' => 'SD',
    ],
    'Suriname' => [
        'name' => 'Suriname',
        'continent' => 'Americas',
        'continent_code' => '019',
        'subcontinent' => 'South America',
        'subcontinent_code' => '005',
        'country_code' => 'SR',
    ],
    'Svalbard & Jan Mayen' => [
        'name' => 'Svalbard & Jan Mayen',
        'continent' => 'Europe',
        'continent_code' => '150',
        'subcontinent' => 'Northern Europe',
        'subcontinent_code' => '154',
        'country_code' => 'SJ',
    ],
    'Sweden' => [
        'name' => 'Sweden',
        'continent' => 'Europe',
        'continent_code' => '150',
        'subcontinent' => 'Northern Europe',
        'subcontinent_code' => '154',
        'country_code' => 'SE',
    ],
    'Switzerland' => [
        'name' => 'Switzerland',
        'continent' => 'Europe',
        'continent_code' => '150',
        'subcontinent' => 'Western Europe',
        'subcontinent_code' => '155',
        'country_code' => 'CH',
    ],
    'Syria' => [
        'name' => 'Syria',
        'continent' => 'Asia',
        'continent_code' => '142',
        'subcontinent' => 'Western Asia',
        'subcontinent_code' => '145',
        'country_code' => 'SY',
    ],
    'São Tomé & Príncipe' => [
        'name' => 'São Tomé & Príncipe',
        'continent' => 'Africa',
        'continent_code' => '002',
        'subcontinent' => 'Middle Africa',
        'subcontinent_code' => '017',
        'country_code' => 'ST',
    ],
    'Taiwan' => [
        'name' => 'Taiwan',
        'continent' => 'Asia',
        'continent_code' => '142',
        'subcontinent' => 'Eastern Asia',
        'subcontinent_code' => '030',
        'country_code' => 'TW',
    ],
    'Tajikistan' => [
        'name' => 'Tajikistan',
        'continent' => 'Asia',
        'continent_code' => '142',
        'subcontinent' => 'Central Asia',
        'subcontinent_code' => '143',
        'country_code' => 'TJ',
    ],
    'Tanzania' => [
        'name' => 'Tanzania',
        'continent' => 'Africa',
        'continent_code' => '002',
        'subcontinent' => 'Eastern Africa',
        'subcontinent_code' => '014',
        'country_code' => 'TZ',
    ],
    'Thailand' => [
        'name' => 'Thailand',
        'continent' => 'Asia',
        'continent_code' => '142',
        'subcontinent' => 'Southeast Asia',
        'subcontinent_code' => '035',
        'country_code' => 'TH',
    ],
    'Timor-Leste' => [
        'name' => 'Timor-Leste',
        'continent' => 'Asia',
        'continent_code' => '142',
        'subcontinent' => 'Southeast Asia',
        'subcontinent_code' => '035',
        'country_code' => 'TL',
    ],
    'Togo' => [
        'name' => 'Togo',
        'continent' => 'Africa',
        'continent_code' => '002',
        'subcontinent' => 'Western Africa',
        'subcontinent_code' => '011',
        'country_code' => 'TG',
    ],
    'Tokelau' => [
        'name' => 'Tokelau',
        'continent' => 'Oceania',
        'continent_code' => '009',
        'subcontinent' => 'Polynesia',
        'subcontinent_code' => '061',
        'country_code' => 'TK',
    ],
    'Tonga' => [
        'name' => 'Tonga',
        'continent' => 'Oceania',
        'continent_code' => '009',
        'subcontinent' => 'Polynesia',
        'subcontinent_code' => '061',
        'country_code' => 'TO',
    ],
    'Trinidad & Tobago' => [
        'name' => 'Trinidad & Tobago',
        'continent' => 'Americas',
        'continent_code' => '019',
        'subcontinent' => 'Caribbean',
        'subcontinent_code' => '029',
        'country_code' => 'TT',
    ],
    'Tristan da Cunha' => [
        'name' => 'Tristan da Cunha',
        'continent' => 'Oceania',
        'continent_code' => '009',
        'subcontinent' => 'Outlying Oceania',
        'subcontinent_code' => 'QO',
        'country_code' => 'TA',
    ],
    'Tunisia' => [
        'name' => 'Tunisia',
        'continent' => 'Africa',
        'continent_code' => '002',
        'subcontinent' => 'Northern Africa',
        'subcontinent_code' => '015',
        'country_code' => 'TN',
    ],
    'Turkmenistan' => [
        'name' => 'Turkmenistan',
        'continent' => 'Asia',
        'continent_code' => '142',
        'subcontinent' => 'Central Asia',
        'subcontinent_code' => '143',
        'country_code' => 'TM',
    ],
    'Turks & Caicos Islands' => [
        'name' => 'Turks & Caicos Islands',
        'continent' => 'Americas',
        'continent_code' => '019',
        'subcontinent' => 'Caribbean',
        'subcontinent_code' => '029',
        'country_code' => 'TC',
    ],
    'Tuvalu' => [
        'name' => 'Tuvalu',
        'continent' => 'Oceania',
        'continent_code' => '009',
        'subcontinent' => 'Polynesia',
        'subcontinent_code' => '061',
        'country_code' => 'TV',
    ],
    'Türkiye' => [
        'name' => 'Türkiye',
        'continent' => 'Asia',
        'continent_code' => '142',
        'subcontinent' => 'Western Asia',
        'subcontinent_code' => '145',
        'country_code' => 'TR',
    ],
    'U.S. Outlying Islands' => [
        'name' => 'U.S. Outlying Islands',
        'continent' => 'Oceania',
        'continent_code' => '009',
        'subcontinent' => 'Micronesian Region',
        'subcontinent_code' => '057',
        'country_code' => 'UM',
    ],
    'U.S. Virgin Islands' => [
        'name' => 'U.S. Virgin Islands',
        'continent' => 'Americas',
        'continent_code' => '019',
        'subcontinent' => 'Caribbean',
        'subcontinent_code' => '029',
        'country_code' => 'VI',
    ],
    'Uganda' => [
        'name' => 'Uganda',
        'continent' => 'Africa',
        'continent_code' => '002',
        'subcontinent' => 'Eastern Africa',
        'subcontinent_code' => '014',
        'country_code' => 'UG',
    ],
    'Ukraine' => [
        'name' => 'Ukraine',
        'continent' => 'Europe',
        'continent_code' => '150',
        'subcontinent' => 'Eastern Europe',
        'subcontinent_code' => '151',
        'country_code' => 'UA',
    ],
    'United Arab Emirates' => [
        'name' => 'United Arab Emirates',
        'continent' => 'Asia',
        'continent_code' => '142',
        'subcontinent' => 'Western Asia',
        'subcontinent_code' => '145',
        'country_code' => 'AE',
    ],
    'United Kingdom' => [
        'name' => 'United Kingdom',
        'continent' => 'Europe',
        'continent_code' => '150',
        'subcontinent' => 'Northern Europe',
        'subcontinent_code' => '154',
        'country_code' => 'GB',
    ],
    'United States' => [
        'name' => 'United States',
        'continent' => 'Americas',
        'continent_code' => '019',
        'subcontinent' => 'Northern America',
        'subcontinent_code' => '021',
        'country_code' => 'US',
    ],
    'Uruguay' => [
        'name' => 'Uruguay',
        'continent' => 'Americas',
        'continent_code' => '019',
        'subcontinent' => 'South America',
        'subcontinent_code' => '005',
        'country_code' => 'UY',
    ],
    'Uzbekistan' => [
        'name' => 'Uzbekistan',
        'continent' => 'Asia',
        'continent_code' => '142',
        'subcontinent' => 'Central Asia',
        'subcontinent_code' => '143',
        'country_code' => 'UZ',
    ],
    'Vanuatu' => [
        'name' => 'Vanuatu',
        'continent' => 'Oceania',
        'continent_code' => '009',
        'subcontinent' => 'Melanesia',
        'subcontinent_code' => '054',
        'country_code' => 'VU',
    ],
    'Vatican City' => [
        'name' => 'Vatican City',
        'continent' => 'Europe',
        'continent_code' => '150',
        'subcontinent' => 'Southern Europe',
        'subcontinent_code' => '039',
        'country_code' => 'VA',
    ],
    'Venezuela' => [
        'name' => 'Venezuela',
        'continent' => 'Americas',
        'continent_code' => '019',
        'subcontinent' => 'South America',
        'subcontinent_code' => '005',
        'country_code' => 'VE',
    ],
    'Vietnam' => [
        'name' => 'Vietnam',
        'continent' => 'Asia',
        'continent_code' => '142',
        'subcontinent' => 'Southeast Asia',
        'subcontinent_code' => '035',
        'country_code' => 'VN',
    ],
    'Wallis & Futuna' => [
        'name' => 'Wallis & Futuna',
        'continent' => 'Oceania',
        'continent_code' => '009',
        'subcontinent' => 'Polynesia',
        'subcontinent_code' => '061',
        'country_code' => 'WF',
    ],
    'Western Sahara' => [
        'name' => 'Western Sahara',
        'continent' => 'Africa',
        'continent_code' => '002',
        'subcontinent' => 'Northern Africa',
        'subcontinent_code' => '015',
        'country_code' => 'EH',
    ],
    'Yemen' => [
        'name' => 'Yemen',
        'continent' => 'Asia',
        'continent_code' => '142',
        'subcontinent' => 'Western Asia',
        'subcontinent_code' => '145',
        'country_code' => 'YE',
    ],
    'Zambia' => [
        'name' => 'Zambia',
        'continent' => 'Africa',
        'continent_code' => '002',
        'subcontinent' => 'Eastern Africa',
        'subcontinent_code' => '014',
        'country_code' => 'ZM',
    ],
    'Zimbabwe' => [
        'name' => 'Zimbabwe',
        'continent' => 'Africa',
        'continent_code' => '002',
        'subcontinent' => 'Eastern Africa',
        'subcontinent_code' => '014',
        'country_code' => 'ZW',
    ],
    'Åland Islands' => [
        'name' => 'Åland Islands',
        'continent' => 'Europe',
        'continent_code' => '150',
        'subcontinent' => 'Northern Europe',
        'subcontinent_code' => '154',
        'country_code' => 'AX',
    ],

    'Aotearoa New Zealand' => [
        'continent' => 'Oceania',
        'continent_code' => '009',
        'subcontinent' => 'Australia and New Zealand',
        'subcontinent_code' => '053',
        'country_code' => 'NZ',
    ],
    
    'Bosnia' => [
        'continent' => 'Europe',
        'continent_code' => '150',
        'subcontinent' => 'Southern Europe',
        'subcontinent_code' => '039',
        'country_code' => 'BA',
    ],
    
    'Cabo Verde' => [
        'continent' => 'Africa',
        'continent_code' => '002',
        'subcontinent' => 'Western Africa',
        'subcontinent_code' => '011',
        'country_code' => 'CV',
    ],
    
    'Chagos Archipelago' => [
        'continent' => 'Africa',
        'continent_code' => '002',
        'subcontinent' => 'Eastern Africa',
        'subcontinent_code' => '014',
        'country_code' => 'IO',
    ],
    
    'Cocos Islands' => [
        'continent' => 'Oceania',
        'continent_code' => '009',
        'subcontinent' => 'Australia and New Zealand',
        'subcontinent_code' => '053',
        'country_code' => 'CC',
    ],
    
    'Congo (DRC)' => [
        'continent' => 'Africa',
        'continent_code' => '002',
        'subcontinent' => 'Middle Africa',
        'subcontinent_code' => '017',
        'country_code' => 'CD',
    ],
    
    'Congo (Republic)' => [
        'continent' => 'Africa',
        'continent_code' => '002',
        'subcontinent' => 'Middle Africa',
        'subcontinent_code' => '017',
        'country_code' => 'CG',
    ],
    
    'Czech Republic' => [
        'continent' => 'Europe',
        'continent_code' => '150',
        'subcontinent' => 'Eastern Europe',
        'subcontinent_code' => '151',
        'country_code' => 'CZ',
    ],
    
    'East Timor' => [
        'continent' => 'Asia',
        'continent_code' => '142',
        'subcontinent' => 'South-eastern Asia',
        'subcontinent_code' => '035',
        'country_code' => 'TL',
    ],
    
    'Falkland Islands (Islas Malvinas)' => [
        'continent' => 'Americas',
        'continent_code' => '019',
        'subcontinent' => 'South America',
        'subcontinent_code' => '005',
        'country_code' => 'FK',
    ],
    
    'Hong Kong' => [
        'continent' => 'Asia',
        'continent_code' => '142',
        'subcontinent' => 'Eastern Asia',
        'subcontinent_code' => '030',
        'country_code' => 'HK',
    ],
    
    'Ivory Coast' => [
        'continent' => 'Africa',
        'continent_code' => '002',
        'subcontinent' => 'Western Africa',
        'subcontinent_code' => '011',
        'country_code' => 'CI',
    ],
    
    'Macao' => [
        'continent' => 'Asia',
        'continent_code' => '142',
        'subcontinent' => 'Eastern Asia',
        'subcontinent_code' => '030',
        'country_code' => 'MO',
    ],
    
    'Myanmar' => [
        'continent' => 'Asia',
        'continent_code' => '142',
        'subcontinent' => 'South-eastern Asia',
        'subcontinent_code' => '035',
        'country_code' => 'MM',
    ],
    
    'Palestine' => [
        'continent' => 'Asia',
        'continent_code' => '142',
        'subcontinent' => 'Western Asia',
        'subcontinent_code' => '145',
        'country_code' => 'PS',
    ],
    
    'Pitcairn' => [
        'continent' => 'Oceania',
        'continent_code' => '009',
        'subcontinent' => 'Polynesia',
        'subcontinent_code' => '061',
        'country_code' => 'PN',
    ],
    
    'Swaziland' => [
        'continent' => 'Africa',
        'continent_code' => '002',
        'subcontinent' => 'Southern Africa',
        'subcontinent_code' => '018',
        'country_code' => 'SZ',
    ],
    
    'Turkey' => [
        'continent' => 'Asia',
        'continent_code' => '142',
        'subcontinent' => 'Western Asia',
        'subcontinent_code' => '145',
        'country_code' => 'TR',
    ],
    
    'UK' => [
        'continent' => 'Europe',
        'continent_code' => '150',
        'subcontinent' => 'Northern Europe',
        'subcontinent_code' => '154',
        'country_code' => 'GB',
    ],
    'US' => [
        'continent' => 'Americas',
        'continent_code' => '019',
        'subcontinent' => 'Northern America',
        'subcontinent_code' => '021',
        'country_code' => 'US',
    ],
];
